# Generated by Django 4.2.9 on 2024-01-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(default="admin", max_length=255),
        ),
        migrations.AlterField(
            model_name="product", name="title", field=models.CharField(max_length=255),
        ),
    ]
